name: CI/CD for React App

on:
  push:
    branches:
      - Main
  pull_request:
    branches:
      - Main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Skip Tests for CI/CD Demo
        run: echo "Skipped tests for this class demo"

      - name: Build React App
        run: CI=false npm run build
